apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: emqx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: emqx.viaduct.testbed
    http:
      paths:
      - path: /
        backend:
          serviceName: emqx-cluster-headless
          servicePort: 18083
