apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubeless-ingress
  namespace: kubeless
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: kubeless.viaduct.testbed
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 3000 
